basePath: /
definitions:
  handler.errorResponce:
    properties:
      message:
        type: string
    type: object
  handler.statusResponse:
    properties:
      status:
        type: string
    type: object
  models.Address:
    properties:
      address:
        type: string
    type: object
  models.GetProducts:
    properties:
      image:
        type: string
      name:
        type: string
      price:
        type: number
    type: object
  models.Login:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  models.Status:
    properties:
      status_id:
        type: integer
    type: object
  models.User:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      phone_number:
        type: string
    required:
    - email
    - name
    - password
    - phone_number
    type: object
host: localhost:8080
info:
  contact: {}
  description: API server for online shop application
  title: Online Shop App
paths:
  /api/admin/orders:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponce'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponce'
      security:
      - ApiKeyAuth: []
      summary: all orders
      tags:
      - Admin
  /api/admin/orders/{id}:
    put:
      consumes:
      - application/json
      parameters:
      - description: order id
        in: path
        name: id
        required: true
        type: string
      - description: new status
        in: body
        name: status
        required: true
        schema:
          $ref: '#/definitions/models.Status'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.statusResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponce'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponce'
      security:
      - ApiKeyAuth: []
      summary: edit order status
      tags:
      - Admin
  /api/admin/products:
    post:
      consumes:
      - application/json
      parameters:
      - description: product name
        in: formData
        name: name
        required: true
        type: string
      - description: poster
        in: formData
        name: image
        required: true
        type: file
      - description: price
        in: formData
        name: price
        required: true
        type: string
      - description: height
        in: formData
        name: height
        required: true
        type: string
      - description: size
        in: formData
        name: size
        required: true
        type: string
      - description: instruction
        in: formData
        name: instruction
        type: string
      - description: description
        in: formData
        name: description
        required: true
        type: string
      - collectionFormat: csv
        description: recommended products
        in: formData
        items:
          type: string
        name: recommended_products
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponce'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponce'
      security:
      - ApiKeyAuth: []
      summary: Create product
      tags:
      - Admin
  /api/admin/products/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: product id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.statusResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponce'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponce'
      security:
      - ApiKeyAuth: []
      summary: delete product
      tags:
      - Admin
    put:
      consumes:
      - application/json
      parameters:
      - description: product id
        in: path
        name: id
        required: true
        type: string
      - description: product name
        in: formData
        name: name
        type: string
      - description: poster
        in: formData
        name: image
        type: file
      - description: price
        in: formData
        name: price
        type: string
      - description: height
        in: formData
        name: height
        type: string
      - description: size
        in: formData
        name: size
        type: string
      - description: instruction
        in: formData
        name: instruction
        type: string
      - description: description
        in: formData
        name: description
        type: string
      - collectionFormat: csv
        description: recommended products
        in: formData
        items:
          type: string
        name: recommended_products
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponce'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponce'
      security:
      - ApiKeyAuth: []
      summary: edit the product
      tags:
      - Admin
  /api/cart:
    delete:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponce'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponce'
      security:
      - ApiKeyAuth: []
      summary: clear the cart
      tags:
      - cart
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponce'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponce'
      security:
      - ApiKeyAuth: []
      summary: All in cart
      tags:
      - cart
  /api/cart/minus/{id}:
    put:
      consumes:
      - application/json
      parameters:
      - description: product id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.statusResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponce'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponce'
      security:
      - ApiKeyAuth: []
      summary: decrease the quantity by one
      tags:
      - cart
  /api/cart/order:
    post:
      consumes:
      - application/json
      parameters:
      - description: address
        in: body
        name: address
        required: true
        schema:
          $ref: '#/definitions/models.Address'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponce'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponce'
      security:
      - ApiKeyAuth: []
      summary: make order
      tags:
      - order
  /api/cart/orders:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponce'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponce'
      security:
      - ApiKeyAuth: []
      summary: order history
      tags:
      - order
  /api/cart/plus/{id}:
    put:
      consumes:
      - application/json
      parameters:
      - description: product id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponce'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponce'
      security:
      - ApiKeyAuth: []
      summary: increase the quantity by one
      tags:
      - cart
  /api/products:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GetProducts'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponce'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponce'
      security:
      - ApiKeyAuth: []
      summary: All products
      tags:
      - product
  /api/products/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: product id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.statusResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponce'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponce'
      security:
      - ApiKeyAuth: []
      summary: product by id
      tags:
      - product
    post:
      consumes:
      - application/json
      parameters:
      - description: product id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.statusResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponce'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponce'
      security:
      - ApiKeyAuth: []
      summary: add to cart
      tags:
      - cart
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: email password
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.Login'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponce'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponce'
      summary: LogIn
      tags:
      - auth
  /auth/signup:
    post:
      consumes:
      - application/json
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponce'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponce'
      summary: SignUp
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
